//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redbrick.csproj.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Driver={SQL Server};SERVER=AMSTORE-SQL-05;DATABASE=ENGINEERING")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Top {
            get {
                return ((int)(this["Top"]));
            }
            set {
                this["Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Left {
            get {
                return ((int)(this["Left"]));
            }
            set {
                this["Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int RevLimit {
            get {
                return ((int)(this["RevLimit"]));
            }
            set {
                this["RevLimit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>BS</string>
  <string>CD</string>
  <string>CW</string>
  <string>DF</string>
  <string>DH</string>
  <string>ED</string>
  <string>JB</string>
  <string>KC</string>
  <string>KL</string>
  <string>LF</string>
  <string>SP</string>
  <string>TH</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Authors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Authors"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ACRYLIC</string>
  <string>ALUMINUM</string>
  <string>BENDER</string>
  <string>CRS</string>
  <string>FELT</string>
  <string>GLASS FL</string>
  <string>GLASS LAM</string>
  <string>GLASS TMP</string>
  <string>HPL</string>
  <string>HRS</string>
  <string>MDF</string>
  <string>MEL</string>
  <string>OFF ALL</string>
  <string>PB</string>
  <string>PC</string>
  <string>PE</string>
  <string>PLWD</string>
  <string>POPLAR</string>
  <string>POSTFRM MDF</string>
  <string>PVC</string>
  <string>SLAB</string>
  <string>SOLID SURF</string>
  <string>SST</string>
  <string>STYRENE</string>
  <string>VAC PRESS</string>
  <string>VENEER</string>
  <string>VINYL</string>
  <string>VINYL WRAP</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Materials {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Materials"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>JCPENNEY - 220</string>
  <string>KMART - 239</string>
  <string>KOHLS - 201</string>
  <string>MACY'S  - 495</string>
  <string>SEARS - 210</string>
  <string>STERLING-491</string>
  <string>TARGET - 274</string>
  <string>WALGREENS - 510</string>
  <string>WALMART - 505</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Customers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Customers"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int Width {
            get {
                return ((int)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int Height {
            get {
                return ((int)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
    }
}
